name: stardist
channels:
  - defaults
  - nvidia
dependencies:
  - python=3.9
  - jupyter
  - numpy
  - pandas
  - scipy
  - seaborn
  - tqdm
  - ipython
  - tensorboard
  - cudatoolkit=11.*
  - cudnn
  - pip
  - pip:
    - tensorflow
    - csbdeep
    - stardist
    - stardist-napari
    - imageio_ffmpeg    
    - gputools
    - napari[all]
